### ISSUE TITLE
Standard issue format

### ISSUE THREAD

**Issue by chrisgbaker** [smashingboxes/boxcar#44]
Much like our PR template, we should create a standard Issues template, so they all follow a similar format.

**Comment by dkniffin** [comment]
We don't use issues much right now, so I'd be curious what this would look like. A lot of times, we even disable issues on our repos

**Comment by chrisgbaker** [comment]
Good point. I think it would have helped me relay the information for this milestone, but if these make enough sense maybe we don't need a template.

**Comment by dkniffin** [comment]
I have wondered what it would be like to replace Jira with Github issues. It would make some things like this a lot easier
