### ISSUE TITLE
Add unit testing tools to help facilitate testing api calls and connected containers

### ISSUE THREAD

**Issue by chrisgbaker** [smashingboxes/boxcar#49]
Libraries Needed:
  - [ ] `fetch-mock`
  - [ ] `sinon`
  - [ ] `enzyme`
  - [ ] `faker.js`
  - [ ] `redux-mock-store` or a good store mocking package

Overall I believe these are pretty good articles on setting up some of these libraries:
https://www.leighhalliday.com/testing-react-jest-enzyme-sinon
https://medium.com/codeclan/testing-react-with-jest-and-enzyme-20505fec4675

**Comment by dkniffin** [comment]
It would be nice to also have a standard factory library. In the past we've used [fixture-factory](https://github.com/peterKaleta/fixture-factory) and it's gone well, but it's pretty dated at this point.
