### ISSUE TITLE
SPIKE: Investigate formik for our form handling Logic

### ISSUE THREAD

**Issue by chrisgbaker** [smashingboxes/boxcar#51]
Some reference
https://redux.js.org/faq/organizing-state#should-i-put-form-state-or-other-ui-state-in-my-store
Basically, redux says you _probably_ don't need your form state in redux. So, I agree 😄 
Their first recommendation: just write it yourself
Their second recommendation: https://goshakkk.name/on-forms-react/
The third, and probably best (?) option, Formik https://github.com/jaredpalmer/formik

Whoever pulls this story should read the above articles, play around with at least the second and third options (we've all done the first in some capacity), and document what they found, and their recommendations moving forward. I can see this getting pulled into an Allhands potentially.

**Comment by chrisgbaker** [comment]
`react-hook-form` is another example which, to me, looks very promising as well, and should be considered. It's smaller, and even in its documentation and examples, shows how you would write the same component with `formik`, `react-hook-form`, and `redux-form`.
https://react-hook-form.com/
https://github.com/react-hook-form/react-hook-form

**Comment by chrisgbaker** [comment]
![image](https://user-images.githubusercontent.com/17983534/69653725-a4ade580-1041-11ea-9059-494b3777ab78.png)


Also, this is taken directly from the top of the documentation for `redux-form`. Is that sort of enough to move forward with *not* putting form state into redux?

**Comment by dkniffin** [comment]
To save people a few clicks, this is the "general consensus": https://redux.js.org/faq/organizing-state#should-i-put-form-state-or-other-ui-state-in-my-store
