### ISSUE TITLE
Decide on a network layer for the frontend

### ISSUE THREAD

**Issue by chrisgbaker** [smashingboxes/boxcar#60]
Native fetch?
Axois?

Whatever we implement, we need to standardize the way a base api/api controller is instantiated, and the way in which to send network requests, deal with failures, manipulate/handle headers, etc.

**Comment by dkniffin** [comment]
I'm fine with the native fetch API, so long as we set up a wrapper that lets us do requests like this `base.get('/whatever/endpoint', {params})` (exact syntax isn't important, but the easy-of-use is), and it handles the following behind the scenes:
- Injecting the baseUrl (eg `https://example.com/api/v1`)
- Some version of axios's interceptors, which would include:
  - Auth header handler
  - 404 redirection -> `/not-found`
  - 401 redirection -> `/log-in`
  - Possibly a loading state updater (eg, at the start of every request, fire off a `NETWORK_REQUEST_START` redux action, and on success or failure, fire another)
  - Possibly the ability to change case from `snake_case` to `camelCase`
